// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Charts: typeof import('./src/components/charts.vue')['default']
    Frequency: typeof import('./src/components/Frequency/Frequency.vue')['default']
    LineBar: typeof import('./src/components/lineBar.vue')['default']
    Maps: typeof import('./src/components/map/maps.vue')['default']
    MapTitle: typeof import('./src/components/map/mapTitle.vue')['default']
    Member: typeof import('./src/components/order/Member.vue')['default']
    Order: typeof import('./src/components/order/Order.vue')['default']
    Physicalunits: typeof import('./src/components/Frequency/Physicalunits.vue')['default']
    Pie: typeof import('./src/components/pie.vue')['default']
    Progress: typeof import('./src/components/Frequency/progress.vue')['default']
    Switch: typeof import('./src/components/Frequency/Switch.vue')['default']
    Table: typeof import('./src/components/table.vue')['default']
    Titles: typeof import('./src/components/map/titles.vue')['default']
    Unit: typeof import('./src/components/Frequency/unit.vue')['default']
  }
}

export {}
